# tensorflow syntax basics

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.13.1


In [3]:
hello = tf.constant("Hello ")

In [14]:
world = tf.constant(' world!...')

In [8]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [15]:
with tf.Session() as sess:
    result = sess.run(hello + world)

In [16]:
result

b'Hello world!...'

In [17]:
a = tf.constant(20)

In [25]:
b = tf.constant(230)

In [33]:
with tf.Session() as sess:
    result1 = sess.run(a + b)
    result2 = sess.run(a * b)
    result3 = sess.run(a / b)

In [34]:
print("result1: ", result1)
print("result2: ", result2)
print("result3: ", result3)

result1:  250
result2:  4600
result3:  0.08695652173913043


In [35]:
const = tf.constant(10)

In [36]:
fil_mat = tf.fill((4,4),10)

In [37]:
myzeros = tf.zeros((4,4))

In [38]:
myones = tf.ones((4,4))

In [39]:
myrandn = tf.random_normal((4,4), mean=0,stddev=1.0)

In [41]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [42]:
my_ops = [const,fil_mat,myzeros,myones,myrandn,myrandu]

In [43]:
sess = tf.InteractiveSession()

In [44]:
for ops in my_ops:
    print(sess.run(ops))
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-0.97159785 -1.0032133   0.85139364 -0.5020466 ]
 [-0.5901505   1.018759    0.04046222  0.34966147]
 [ 1.7385979  -0.6341524  -0.6482128   0.74259555]
 [-0.9756126   2.222164   -1.4881793  -0.72100365]]


[[0.7450799  0.96081984 0.9536209  0.16799295]
 [0.5416175  0.56053865 0.9420538  0.56742215]
 [0.44590843 0.28063965 0.84760976 0.66982543]
 [0.43514323 0.0231446  0.97358537 0.61092687]]




In [45]:
c = tf.constant([[1,2],[3,4]])
d = tf.constant([[10],[100]])

In [47]:
result = tf.matmul(c,d)